### PR TITLE
Add playlist function

### PR DESCRIPTION
**Pull request by ChangSeongBeom**
Add playlist function

### CODE REVIEW

**Comment by ChangSeongBeom** [comment]
And it shows music list in web and users can choose music from that list

**Comment by jboynyc** [comment]
Cool, thanks! I may merge this after I get a chance to test it (I'm not running `cmus` a lot these days).

**Comment by ChangSeongBeom** [comment]
Okay, I am trying to develop this function corrently(this code happen a little error because of compatibility).

**Comment by jboynyc** [comment]
I'm not using `cmus` anymore, so I can't test this. I'll close the PR. Let me know if you'd like me to link to your fork from the README.

**Pull request closed without merging**
